//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper
    {
        public paper()
        {
            this.questions = new HashSet<question>();
            this.solutions = new HashSet<solution>();
        }
    
        public int course_code { get; set; }
        public string subject_name { get; set; }
        public int t_id { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual teacher teacher { get; set; }
        public virtual ICollection<question> questions { get; set; }
        public virtual ICollection<solution> solutions { get; set; }
    }
}
