//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int Qno { get; set; }
        public string Qdescription { get; set; }
        public int course_code { get; set; }
    
        public virtual paper paper { get; set; }
        public virtual question question1 { get; set; }
        public virtual question question2 { get; set; }
        public virtual question question11 { get; set; }
        public virtual question question3 { get; set; }
        public virtual question question12 { get; set; }
        public virtual question question4 { get; set; }
    }
}
