//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solution
    {
        public int ansno { get; set; }
        public string ans_description { get; set; }
        public Nullable<int> course_code { get; set; }
    
        public virtual paper paper { get; set; }
    }
}
