//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.courses = new HashSet<course>();
        }
    
        public int id { get; set; }
        public string stu_name { get; set; }
        public Nullable<int> stu_phone { get; set; }
        public string major { get; set; }
        public Nullable<int> t_id { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<course> courses { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
