//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public teacher()
        {
            this.papers = new HashSet<paper>();
            this.students = new HashSet<student>();
        }
    
        public int t_id { get; set; }
        public string t_name { get; set; }
        public string rank { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<paper> papers { get; set; }
        public virtual ICollection<student> students { get; set; }
    }
}
